<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="O’Malley, Conie">
<meta name="dcterms.date" content="2025-02-25">

<title>ITEC 621 - Homework 3 - Cross Validation and Dimensionality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW3_O-Malley_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW3_O-Malley_files/libs/quarto-html/quarto.js"></script>
<script src="HW3_O-Malley_files/libs/quarto-html/popper.min.js"></script>
<script src="HW3_O-Malley_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW3_O-Malley_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW3_O-Malley_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW3_O-Malley_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW3_O-Malley_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW3_O-Malley_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW3_O-Malley_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ITEC 621 - Homework 3 - Cross Validation and Dimensionality</h1>
<p class="subtitle lead">Kogod School of Business</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>O’Malley, Conie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 25, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="submission" class="level2">
<h2 class="anchored" data-anchor-id="submission">Submission:</h2>
<p>Download the <strong>HW3_YourLastName.Rmd</strong> R Markdown file and save it with <strong>your own last name</strong>. <font color="red">Note, it is important that you conform to this file naming convention</font>, otherwise it will affect the sorting of assignments for us. Please name your file as instructed and complete all your work in that template file, <strong>Knit</strong> the corresponding Word or PDF file. Your knitted file <strong>MUST display your R commands</strong>. In order to do this, please ensure that the <code>knittr::</code> global option command above has <code>echo=T</code>.</p>
</section>
<section id="specific-instructions" class="level2">
<h2 class="anchored" data-anchor-id="specific-instructions">Specific Instructions</h2>
</section>
<section id="knitting-writing-and-professional-presentation" class="level2">
<h2 class="anchored" data-anchor-id="knitting-writing-and-professional-presentation">Knitting, Writing and Professional Presentation</h2>
<p>One of the goals of HW’s and Exercises is to practice with effective and <strong>professional R Markdown analytics report production</strong>. You are expected to prepare and produce your knitted document in a professional manner. Up to 10 points will be deducted for improper or no knitting and professional appearance. The main criteria is how acceptable your report would be for a buiness management or client audience, including: proper use of fonts, punctuation and sentence structure; lack of grammatical and spelling errors; and clear and succint articulation of narratives; among other things. Please note that this section is about report formatting and presentation. The quality and completeness of your answers will be graded separately in each question below.</p>
<p><strong>Resources:</strong> Please make an appointment with the <strong>KCBC</strong> if you need help with the writing and presentations. The KCBC has a wonderful team of TA’s ready and eager to help with the writing. If you are an international student, please make an appointment with Shari Patillo, Associate Director of International Student Development. She is also very interested and eager to help international students, but all students are welcome.</p>
</section>
<section id="pts.-multi-collinearity-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pts.-multi-collinearity-analysis">1. (20 pts.) Multi-Collinearity Analysis</h2>
<p>Load the <strong>{ISLR}</strong> library, which contains the <strong>College</strong> data set. Then type <code>?College</code> in the console (not in the script) and familiarize yourself with the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(College)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>1.1 Fit a full model to predict <strong>applications</strong> using <strong>all</strong> remaining variables as predictors and name it <strong>lm.fit.all</strong>. Then display the <code>summary()</code> of this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>lm.fit.all <span class="ot">&lt;-</span> <span class="fu">lm</span>(Apps <span class="sc">~</span> ., <span class="at">data =</span> College)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit.all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Apps ~ ., data = College)

Residuals:
    Min      1Q  Median      3Q     Max 
-4908.8  -430.2   -29.5   322.3  7852.5 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -445.08413  408.32855  -1.090 0.276053    
PrivateYes  -494.14897  137.81191  -3.586 0.000358 ***
Accept         1.58581    0.04074  38.924  &lt; 2e-16 ***
Enroll        -0.88069    0.18596  -4.736 2.60e-06 ***
Top10perc     49.92628    5.57824   8.950  &lt; 2e-16 ***
Top25perc    -14.23448    4.47914  -3.178 0.001543 ** 
F.Undergrad    0.05739    0.03271   1.754 0.079785 .  
P.Undergrad    0.04445    0.03214   1.383 0.167114    
Outstate      -0.08587    0.01906  -4.506 7.64e-06 ***
Room.Board     0.15103    0.04829   3.127 0.001832 ** 
Books          0.02090    0.23841   0.088 0.930175    
Personal       0.03110    0.06308   0.493 0.622060    
PhD           -8.67850    4.63814  -1.871 0.061714 .  
Terminal      -3.33066    5.09494  -0.654 0.513492    
S.F.Ratio     15.38961   13.00622   1.183 0.237081    
perc.alumni    0.17867    4.10230   0.044 0.965273    
Expend         0.07790    0.01235   6.308 4.79e-10 ***
Grad.Rate      8.66763    2.94893   2.939 0.003390 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1041 on 759 degrees of freedom
Multiple R-squared:  0.9292,    Adjusted R-squared:  0.9276 
F-statistic: 585.9 on 17 and 759 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>1.2 Then, load the <strong>{klaR}</strong> (for CI) and <strong>{car}</strong> (for VIF’s) libraries. Obtain the <strong>Condition Index (CI)</strong> for this model using the <code>cond.index()</code>. That is, feed the <strong>lm.fit.all</strong> model into this function, along with the <code>data = College</code> parameter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(klaR)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>klaR<span class="sc">::</span><span class="fu">cond.index</span>(lm.fit.all, <span class="at">data =</span> College) <span class="co"># calculate CI</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.000000  2.650021  4.960084  6.383467  8.609577  9.618359 10.716476
 [8] 11.974004 13.918283 15.120624 18.815725 20.313196 22.308564 25.147448
[15] 28.557217 30.886931 44.312276 51.983354</code></pre>
</div>
</div>
<p>1.3 Then load the <strong>{car}</strong> library and then compute and display the Variance Inflation Factors <strong>(VIF’s)</strong> for the predictors in the model using the <code>vif()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(lm.fit.all) <span class="co"># calculate VIFs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Private      Accept      Enroll   Top10perc   Top25perc F.Undergrad 
   2.699896    7.136020   21.365412    6.929185    5.631213   18.017997 
P.Undergrad    Outstate  Room.Board       Books    Personal         PhD 
   1.713431    4.205568    2.007318    1.108744    1.305171    4.104258 
   Terminal   S.F.Ratio perc.alumni      Expend   Grad.Rate 
   4.026296    1.896717    1.849254    2.975392    1.836249 </code></pre>
</div>
</div>
<p>1.4 Do the CI and VIF’s provide evidence of severe multicollinearity with the model? Why or why not? Which variables seem to be the problem.</p>
<p>Yes, there is evidence of severe multicollinearity based on the <code>CI</code> of 51.9833 and the <code>VIF</code>s of 21.3654 and 18.0179 for the variables <code>Enroll</code> and <code>F.Undergrad</code>, respectively.</p>
<p>1.5 Fit a <strong>reduced</strong> model to predict <strong>Apps</strong> on <strong>Enroll</strong> and <strong>Top10perc</strong> only. Name it <strong>lm.fit.reduced</strong>. Display: (a) the model summary results; (b) the CI, but this time using <code>scale=T, center=T, add.intercept=F</code>; and (c) the VIF’s.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lm.fit.reduced <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(Apps <span class="sc">~</span> Enroll <span class="sc">+</span> Top10perc, College) <span class="co"># fit a reduced model</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit.reduced) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Apps ~ Enroll + Top10perc, data = College)

Residuals:
   Min     1Q Median     3Q    Max 
 -9468   -666   -115    409  32087 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -795.11465  134.15208  -5.927 4.64e-09 ***
Enroll         3.38249    0.07572  44.671  &lt; 2e-16 ***
Top10perc     42.03776    3.98841  10.540  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1927 on 774 degrees of freedom
Multiple R-squared:  0.7526,    Adjusted R-squared:  0.752 
F-statistic:  1177 on 2 and 774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>klaR<span class="sc">::</span><span class="fu">cond.index</span>(lm.fit.reduced, <span class="at">scale =</span> T, <span class="at">center =</span> T, <span class="at">add.intercept=</span>F, <span class="at">data =</span> College) <span class="co"># calculate CI</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.00000 2.34743 3.91938</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(lm.fit.reduced) <span class="co"># calculate VIFs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Enroll Top10perc 
 1.033984  1.033984 </code></pre>
</div>
</div>
<p>1.6 Was the multi-collinearity problem eliminated? Why or why not?</p>
<section id="analysis" class="level4">
<h4 class="anchored" data-anchor-id="analysis">Analysis</h4>
<p>Yes, multicollinearity was addressed because the Condition Index and Variable Inflation Factors dropped to acceptable levels <span class="math inline">\(CI &lt; 50\)</span> and <span class="math inline">\(VIF_i &lt; 10\)</span>, respectively.</p>
</section>
</section>
<section id="pts.-variable-selection-with-stepwise" class="level2">
<h2 class="anchored" data-anchor-id="pts.-variable-selection-with-stepwise">2. (20 pts.) Variable Selection with Stepwise</h2>
<p>2.1 Let’s try the <strong>Stepwise</strong> approach to variable selection to find an optimal model between <strong>lm.fit.reduced</strong> and <strong>lm.fit.large</strong>. We already have <strong>lm.fit.reduced</strong> so let’s fit the larger model <strong>lm.fit.large</strong> with all variables that make sense from a business standpoint. Display the <code>summary()</code> results for <strong>lm.fit.large</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>lm.fit.large <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(Apps<span class="sc">~</span>Enroll<span class="sc">+</span>Top10perc<span class="sc">+</span>Outstate<span class="sc">+</span>Room.Board<span class="sc">+</span>PhD<span class="sc">+</span>S.F.Ratio<span class="sc">+</span>Expend<span class="sc">+</span>Grad.Rate,<span class="at">data=</span>College)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit.large)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Apps ~ Enroll + Top10perc + Outstate + Room.Board + 
    PhD + S.F.Ratio + Expend + Grad.Rate, data = College)

Residuals:
    Min      1Q  Median      3Q     Max 
-8652.4  -617.6  -114.7   474.0 31465.0 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -3.922e+03  5.586e+02  -7.023 4.80e-12 ***
Enroll       3.416e+00  8.293e-02  41.187  &lt; 2e-16 ***
Top10perc    1.613e+01  5.689e+00   2.834  0.00471 ** 
Outstate    -3.656e-02  2.940e-02  -1.243  0.21408    
Room.Board   4.400e-01  8.062e-02   5.458 6.49e-08 ***
PhD         -4.122e+00  5.146e+00  -0.801  0.42336    
S.F.Ratio    4.704e+01  2.229e+01   2.110  0.03519 *  
Expend       9.719e-02  2.104e-02   4.619 4.52e-06 ***
Grad.Rate    1.493e+01  4.875e+00   3.064  0.00226 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1827 on 768 degrees of freedom
Multiple R-squared:  0.7796,    Adjusted R-squared:  0.7773 
F-statistic: 339.5 on 8 and 768 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Use the <code>step()</code> function to run a <strong>stepwise</strong> variable selection process. Save the stepwise results in an object named <strong>lm.stepwise</strong>. As you know, the stepwise approach can start with the larger model and go backwards, or with the reduced model and proceed forward. Let’s do the backwards stepwise by entering <strong>lm.fit.large</strong> as the starting base.</p>
<p>Use the <code>scope=list()</code> function from the <strong>lower</strong> bound model of <strong>lm.fit.reduced</strong> and the <strong>upper</strong> bound model of <strong>lm.fit.large</strong>. This will limit the set of stepwise models tried to only those within this scope. Also, in both cases, use <code>direction="both"</code> (that is, stepwise) and <code>test="F"</code> to get p-values for the predictors.</p>
<p>After run the stepwise variable selection process, display the <code>summary()</code> results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(Apps <span class="sc">~</span> <span class="dv">0</span>, College) <span class="co"># fit a null model that I didn't end up using</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>lm.stepwise <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">step</span>(lm.fit.large, <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span>lm.fit.reduced, <span class="at">upper=</span>lm.fit.large),  </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">direction=</span><span class="st">"both"</span>, <span class="at">test=</span><span class="st">"F"</span>) <span class="co"># run stepwise regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=11679.79
Apps ~ Enroll + Top10perc + Outstate + Room.Board + PhD + S.F.Ratio + 
    Expend + Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
- PhD         1   2140775 2564455998 11678  0.6417  0.423361    
- Outstate    1   5158573 2567473795 11679  1.5462  0.214081    
&lt;none&gt;                    2562315222 11680                      
- S.F.Ratio   1  14851935 2577167157 11682  4.4516  0.035192 *  
- Grad.Rate   1  31313260 2593628482 11687  9.3855  0.002264 ** 
- Expend      1  71183114 2633498336 11699 21.3356 4.519e-06 ***
- Room.Board  1  99401404 2661716627 11707 29.7935 6.490e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=11678.44
Apps ~ Enroll + Top10perc + Outstate + Room.Board + S.F.Ratio + 
    Expend + Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
- Outstate    1   6101776 2570557773 11678  1.8297  0.176557    
&lt;none&gt;                    2564455998 11678                      
+ PhD         1   2140775 2562315222 11680  0.6417  0.423361    
- S.F.Ratio   1  13718120 2578174118 11681  4.1136  0.042883 *  
- Grad.Rate   1  31183379 2595639376 11686  9.3509  0.002306 ** 
- Expend      1  69627645 2634083643 11697 20.8791 5.697e-06 ***
- Room.Board  1  97587525 2662043522 11706 29.2634 8.443e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=11678.28
Apps ~ Enroll + Top10perc + Room.Board + S.F.Ratio + Expend + 
    Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
&lt;none&gt;                    2570557773 11678                      
+ Outstate    1   6101776 2564455998 11678  1.8297  0.176557    
+ PhD         1   3083978 2567473795 11679  0.9237  0.336807    
- S.F.Ratio   1  17375420 2587933194 11682  5.2047  0.022798 *  
- Grad.Rate   1  25691863 2596249636 11684  7.6959  0.005669 ** 
- Expend      1  63525871 2634083644 11695 19.0289 1.463e-05 ***
- Room.Board  1  95376286 2665934059 11705 28.5696 1.192e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.stepwise) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Apps ~ Enroll + Top10perc + Room.Board + 
    S.F.Ratio + Expend + Grad.Rate, data = College)

Residuals:
    Min      1Q  Median      3Q     Max 
-8487.7  -651.9  -112.5   477.6 31538.5 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.122e+03  5.256e+02  -7.843 1.47e-14 ***
Enroll       3.422e+00  7.709e-02  44.389  &lt; 2e-16 ***
Top10perc    1.372e+01  5.408e+00   2.536  0.01141 *  
Room.Board   3.875e-01  7.250e-02   5.345 1.19e-07 ***
S.F.Ratio    4.981e+01  2.183e+01   2.281  0.02280 *  
Expend       8.740e-02  2.003e-02   4.362 1.46e-05 ***
Grad.Rate    1.286e+01  4.637e+00   2.774  0.00567 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1827 on 770 degrees of freedom
Multiple R-squared:  0.7788,    Adjusted R-squared:  0.7771 
F-statistic:   452 on 6 and 770 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>2.2 Notice that S.F.Ratio is significant at the p=0.02 level, which is OK for most purposes. However, let’s suppose that for this model you wish to include only variables significant at the p&lt;0.01 level. In this case, you need to include the <code>k=</code> attribute. To find out the value of k to use, enter <code>qchisq(0.01, 1, lower.tail=F)</code>. You should get <strong>6.6</strong>. Thus, entering <code>k=6.6</code> as an attribute in the <code>step()</code> function should yield a more restrictive model. Fit a stepwise model and store the results in an object named <strong>lm.stepwise.01</strong>. Then display its <code>summary()</code> results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">qchisq</span>(<span class="fl">0.01</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="ot">-&gt;</span> k_value</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>lm.stepwise<span class="fl">.01</span> <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">step</span>(lm.fit.large, <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower=</span>lm.fit.reduced, <span class="at">upper=</span>lm.fit.large),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">test =</span> <span class="st">"F"</span>, <span class="at">k =</span> k_value) <span class="co"># fit new stepwise model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=11721.5
Apps ~ Enroll + Top10perc + Outstate + Room.Board + PhD + S.F.Ratio + 
    Expend + Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
- PhD         1   2140775 2564455998 11716  0.6417  0.423361    
- Outstate    1   5158573 2567473795 11716  1.5462  0.214081    
- S.F.Ratio   1  14851935 2577167157 11719  4.4516  0.035192 *  
&lt;none&gt;                    2562315222 11722                      
- Grad.Rate   1  31313260 2593628482 11724  9.3855  0.002264 ** 
- Expend      1  71183114 2633498336 11736 21.3356 4.519e-06 ***
- Room.Board  1  99401404 2661716627 11744 29.7935 6.490e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=11715.52
Apps ~ Enroll + Top10perc + Outstate + Room.Board + S.F.Ratio + 
    Expend + Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
- Outstate    1   6101776 2570557773 11711  1.8297  0.176557    
- S.F.Ratio   1  13718120 2578174118 11713  4.1136  0.042883 *  
&lt;none&gt;                    2564455998 11716                      
- Grad.Rate   1  31183379 2595639376 11718  9.3509  0.002306 ** 
+ PhD         1   2140775 2562315222 11722  0.6417  0.423361    
- Expend      1  69627645 2634083643 11730 20.8791 5.697e-06 ***
- Room.Board  1  97587525 2662043522 11738 29.2634 8.443e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=11710.73
Apps ~ Enroll + Top10perc + Room.Board + S.F.Ratio + Expend + 
    Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
- S.F.Ratio   1  17375420 2587933194 11709  5.2047  0.022798 *  
&lt;none&gt;                    2570557773 11711                      
- Grad.Rate   1  25691863 2596249636 11712  7.6959  0.005669 ** 
+ Outstate    1   6101776 2564455998 11716  1.8297  0.176557    
+ PhD         1   3083978 2567473795 11716  0.9237  0.336807    
- Expend      1  63525871 2634083644 11723 19.0289 1.463e-05 ***
- Room.Board  1  95376286 2665934059 11732 28.5696 1.192e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=11709.33
Apps ~ Enroll + Top10perc + Room.Board + Expend + Grad.Rate

             Df Sum of Sq        RSS   AIC F value    Pr(&gt;F)    
&lt;none&gt;                    2587933194 11709                      
- Grad.Rate   1  23383194 2611316387 11710  6.9663 0.0084735 ** 
+ S.F.Ratio   1  17375420 2570557773 11711  5.2047 0.0227976 *  
+ Outstate    1   9759076 2578174118 11713  2.9147 0.0881813 .  
+ PhD         1   1750276 2586182918 11715  0.5211 0.4705834    
- Expend      1  46720727 2634653920 11717 13.9191 0.0002049 ***
- Room.Board  1  91424463 2679357657 11730 27.2373 2.316e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.stepwise<span class="fl">.01</span>) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Apps ~ Enroll + Top10perc + Room.Board + 
    Expend + Grad.Rate, data = College)

Residuals:
    Min      1Q  Median      3Q     Max 
-8444.9  -637.8  -110.6   436.7 31619.9 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -3.183e+03  3.274e+02  -9.722  &lt; 2e-16 ***
Enroll       3.480e+00  7.290e-02  47.739  &lt; 2e-16 ***
Top10perc    1.326e+01  5.419e+00   2.448 0.014602 *  
Room.Board   3.789e-01  7.260e-02   5.219 2.32e-07 ***
Expend       6.738e-02  1.806e-02   3.731 0.000205 ***
Grad.Rate    1.225e+01  4.642e+00   2.639 0.008473 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1832 on 771 degrees of freedom
Multiple R-squared:  0.7773,    Adjusted R-squared:  0.7759 
F-statistic: 538.4 on 5 and 771 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>2.3 Compare the two stepwise results above. What is the main difference between the 2?</p>
<section id="analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="analysis-1">Analysis</h4>
<p>The <code>S.F.Ratio</code> variable is not longer siginificant to the model and the adjusted <span class="math inline">\(r^2\)</span> value increases with the new model slightly from <span class="math inline">\(r^2 = 0.7771\)</span> to <span class="math inline">\(r^2 = 0.7779\)</span>.</p>
<p>2.4 Notice that <strong>Top10perc</strong> was included in <strong>lm.stepwise.01</strong> even thought p&gt;0.01. Why do you think this happened?</p>
</section>
<section id="analysis-2" class="level4">
<h4 class="anchored" data-anchor-id="analysis-2">Analysis</h4>
<p>Because by including <code>Top10perc</code>, the overall model has a better adjusted <span class="math inline">\(r^2\)</span> value and a smaller AIC value, so it is included in the model. So even though <code>Top10perc</code> is not statistically significant in terms of individual <code>p value</code>, it adds significane to the overall model by its inclusion.</p>
</section>
</section>
<section id="pts.-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="pts.-cross-validation">3. (20 pts.) Cross Validation</h2>
<p>Load the <strong>{car}</strong> library and attach the dataset into your work environment. Run <code>?Salaries</code> from the console (not in the script) and inspect the variables in this dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#library(car)</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Salaries)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="random-splitting-holdout-sample" class="level3">
<h3 class="anchored" data-anchor-id="random-splitting-holdout-sample">Random Splitting (Holdout Sample)</h3>
<p>3.1 Enter <code>set.seed(15)</code> so that you get the same results if you run your cross validation commands multiple times. Then use the <code>sample()</code> function to create an index vector called <strong>train</strong> which you can later use to split the data set into <strong>80%</strong> train subsample.</p>
<p>Also, do a quick inspection of your results by: list the number of rows of the <strong>Salaries</strong> dataset; the length of the <strong>train</strong> vector; the <strong>first 10</strong> values in the <strong>train</strong> vector; and the corresponding 10 first observations in the train subset (tip: use Salaries[train[1:10],], but try to understand why).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">15</span>) <span class="co"># set seed for reproducibility</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Salaries), <span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(Salaries)) <span class="co"># create sample subset</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(Salaries))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 397</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">length</span>(train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 317</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(utils<span class="sc">::</span><span class="fu">head</span>(train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  37 362 162 294 177 261</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Salaries[train[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>],])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         rank discipline yrs.since.phd yrs.service    sex salary
37       Prof          B            22          21   Male 155750
362      Prof          A            23          15 Female 109646
162      Prof          B            26          19   Male 176500
294 AssocProf          A            11           1   Male 104800
177 AssocProf          B            10           7   Male  95436
261 AssocProf          A            41          33   Male  88600
217      Prof          B            15          11   Male 146000
204      Prof          B            17          17   Male 152500
363      Prof          A            30          30   Male 138771
84   AsstProf          B             6           2   Male  88825</code></pre>
</div>
</div>
<p>3.2 Fit a linear model to predict <strong>salary</strong> using all remaining variables as predictors, but using only the <strong>train</strong> data subset. Store your resulting model in an object named <strong>fit.train</strong> and display the <code>summary()</code> results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fit.train <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> Salaries[train,]) <span class="co"># fit linear model</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.train) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = salary ~ ., data = Salaries[train, ])

Residuals:
   Min     1Q Median     3Q    Max 
-66638 -13727  -1157  10652  98491 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    64513.6     5277.7  12.224  &lt; 2e-16 ***
rankAssocProf  11808.8     4750.1   2.486   0.0134 *  
rankProf       45580.5     4930.7   9.244  &lt; 2e-16 ***
disciplineB    14304.5     2713.2   5.272 2.53e-07 ***
yrs.since.phd    637.4      266.9   2.389   0.0175 *  
yrs.service     -565.2      237.6  -2.379   0.0180 *  
sexMale         5910.5     4540.1   1.302   0.1939    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 23300 on 310 degrees of freedom
Multiple R-squared:  0.4668,    Adjusted R-squared:  0.4565 
F-statistic: 45.24 on 6 and 310 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>3.3 Using the <strong>fit.train</strong> model, compute the <strong>MSE</strong> for the <strong>train</strong> and <strong>test</strong> subsets. Store the results in objects named <strong>train.mse</strong> and <strong>test.mse</strong>, respectively. Then, use the <code>c()</code> function to display these two results together with their respective labels <strong>“Train MSE”</strong> and <strong>“Test MSE”</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute train MSE</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>train.mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((Salaries<span class="sc">$</span>salary[train] <span class="sc">-</span> stats<span class="sc">::</span><span class="fu">predict</span>(fit.train, <span class="at">newdata =</span> Salaries[train,]))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute test MSE</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>test.mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((Salaries<span class="sc">$</span>salary[<span class="sc">-</span>train] <span class="sc">-</span> stats<span class="sc">::</span><span class="fu">predict</span>(fit.train, <span class="at">newdata =</span> Salaries[<span class="sc">-</span>train,]))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">"Train MSE"</span> <span class="ot">=</span> train.mse, <span class="st">"Test MSE"</span> <span class="ot">=</span> test.mse) <span class="co"># concatenate into a list</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train MSE  Test MSE 
530935984 380309293 </code></pre>
</div>
</div>
<p>3.4 Briefly comment on the difference between the <strong>Train</strong> and <strong>Test MSE</strong> values. Is this what you expected? Why or why not?</p>
<section id="analysis-3" class="level4">
<h4 class="anchored" data-anchor-id="analysis-3">Analysis</h4>
<p>The MSE of the training data set was greater than that of the test data. That was expected due to the difference in sample sizes of the test and training data. This is what I had expected, although with an 80/20 split, I expected the test MSE to be less than it was in proportion to the train MSE.</p>
</section>
</section>
<section id="leave-one-out-validation-loocv" class="level3">
<h3 class="anchored" data-anchor-id="leave-one-out-validation-loocv">Leave One Out Validation (LOOCV)</h3>
<p>3.5 Using the <strong>Salaries{car}</strong> data set, fit a <strong>GLM</strong> model to predict salary using all predictors. Display the summary results. Store the results in an object named <strong>glm.fit</strong>. Tip: when you use the <code>glm()</code> function you need to specify the family and the link function. However, if you don’t specify a family, the “gaussian” family (i.e., normal distribution) and the “identity” link (i.e., no transformation of the response variable) will be used as defaults. So just use the <code>glm()</code> function exactly how you use the <code>lm()</code> function and the result will be an OLS model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit glm </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>glm.fit <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> Salaries, <span class="at">family =</span> stats<span class="sc">::</span><span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.fit) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = salary ~ ., family = stats::gaussian(link = "identity"), 
    data = Salaries)

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    65955.2     4588.6  14.374  &lt; 2e-16 ***
rankAssocProf  12907.6     4145.3   3.114  0.00198 ** 
rankProf       45066.0     4237.5  10.635  &lt; 2e-16 ***
disciplineB    14417.6     2342.9   6.154 1.88e-09 ***
yrs.since.phd    535.1      241.0   2.220  0.02698 *  
yrs.service     -489.5      211.9  -2.310  0.02143 *  
sexMale         4783.5     3858.7   1.240  0.21584    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 507990599)

    Null deviance: 3.6330e+11  on 396  degrees of freedom
Residual deviance: 1.9812e+11  on 390  degrees of freedom
AIC: 9093.8

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>3.6 Load the <strong>{boot}</strong> library and use the <code>cv.glm()</code> function and the <strong>glm.fit</strong> object above to compute and display the <strong>LOOCV MSE</strong> (Leave One Out) for this model (the first element $delta[1]) contains the raw MSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>loocv <span class="ot">&lt;-</span> boot<span class="sc">::</span><span class="fu">cv.glm</span>(Salaries, glm.fit, <span class="at">K =</span> <span class="fu">nrow</span>(Salaries))<span class="co"># compute LOOCV </span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(loocv<span class="sc">$</span>delta[<span class="dv">1</span>]) <span class="co"># view the raw MSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 516540699</code></pre>
</div>
</div>
<p><strong>Technical Note FYI</strong>: since glm() and lm() can both fit OLS models, some times it is convenient to use one or the other because other useful libraries and functions need either <code>glm()</code> or <code>lm()</code> objects specifically. This is one of these cases – the <code>cv.glm()</code> function only works with <code>glm()</code> objects. However, if you are interested in R-Squares and F-Statistics you and run the same model with lm() and you should get the same results.*</p>
</section>
<section id="k-fold-validation-kfcv" class="level3">
<h3 class="anchored" data-anchor-id="k-fold-validation-kfcv">K-Fold Validation (KFCV)</h3>
<p>3.7 Using the same <strong>cv.glm()</strong> function and <strong>glm.fit</strong> model object, compute and display the <strong>10-Fold</strong> cross validation MSE for this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>cfv10 <span class="ot">&lt;-</span> boot<span class="sc">::</span><span class="fu">cv.glm</span>(Salaries, glm.fit, <span class="at">K =</span> <span class="dv">10</span>) <span class="co"># compute 10-fold CV </span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cfv10<span class="sc">$</span>delta[<span class="dv">1</span>]) <span class="co"># view the raw MSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 524086639</code></pre>
</div>
</div>
<p>3.8 Compare the differences between the <strong>10FCV</strong> result above and this <strong>LOOCV</strong> result and provide a brief concluding comment. Is there a meaning to the difference between these 2 MSE values? Please explain why or why not.</p>
<section id="analysis-4" class="level4">
<h4 class="anchored" data-anchor-id="analysis-4">Analysis</h4>
<p>The <code>LOOCV</code> MSE is much smaller than the <code>10FCV</code> MSE (<span class="math inline">\(516540699 &lt; 524086639\)</span>) because the <code>LOOCV</code> captures a lot of noise and tends to overfit the model by only leaving out one data point per model iteration. The <code>10FCV</code> will introduce more bias into the model in comparison to the <code>LOOCV</code> model will, but the <code>10FCV</code> model will perform better against new because it does not capture the noise that the <code>LOOCV</code> model captures, which is evidenced by the smaller MSE of the <code>LOOCV</code>.</p>
</section>
</section>
</section>
<section id="pts.-ridge-and-lasso" class="level2">
<h2 class="anchored" data-anchor-id="pts.-ridge-and-lasso">4. (20 pts.) Ridge and LASSO</h2>
<p>4.1 Setup: x matrix and y vector (done for you)</p>
<p>First, change the scientific notation with <code>options(scipen=4)</code>.</p>
<p>Then, load the <strong>{glmnet}</strong> and <strong>{ISLR}</strong> libraries. Then run <code>?College</code> in the R Console (not in the script) to view and familiarize yourself with the College data set attributes. Enter <code>College=na.omit(College)</code> to remove all rows with omitted values.</p>
<p>Then, create an <strong>x</strong> predictor matrix with the <code>model.matrix()</code> function with the following variables: <code>Apps~Enroll+Top10perc+Outstate+Room.Board+PhD+S.F.Ratio+Expend+Grad.Rate</code>, from the <strong>College</strong> data set in <strong>{ISLR}</strong>, but remove the intercept (first) column from the resulting matrix with <strong>[,-1]</strong>. Then create the <strong>y</strong> vector using <strong>Apps</strong> column in the <strong>College</strong> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">4</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet) <span class="co"># Contains functions for Ridge and LASSO</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR) <span class="co"># Contains the College data set</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>College<span class="ot">=</span><span class="fu">na.omit</span>(College)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">model.matrix</span>(Apps<span class="sc">~</span>Enroll<span class="sc">+</span>Top10perc<span class="sc">+</span>Outstate<span class="sc">+</span>Room.Board<span class="sc">+</span>PhD<span class="sc">+</span>S.F.Ratio<span class="sc">+</span>Expend<span class="sc">+</span>Grad.Rate, <span class="at">data=</span>College)[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span>College<span class="sc">$</span>Apps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>4.2 Then fit a <strong>Ridge</strong> regression <strong>x</strong> and <strong>y</strong>. Name the resulting object <strong>ridge.mod</strong>. Enter `ridge.mod$lambda[1:6] to view the first 6 lambda values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ridge.mod <span class="ot">&lt;-</span> glmnet<span class="sc">::</span><span class="fu">glmnet</span>(x, y, <span class="at">alpha =</span> <span class="dv">0</span>) <span class="co"># fit a ridge regression model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>ridge.mod<span class="sc">$</span>lambda[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>] <span class="co"># view the first 6 lambda values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3275262 2984297 2719180 2477616 2257511 2056960</code></pre>
</div>
</div>
<p>4.3 Enter <code>set.seed(1)</code> so that your sample matches my results. Then, using the <strong>cv.glmnet()</strong> function in the <strong>{glmnet}</strong> package, compute the cross-validation statistics for the <strong>ridge.mod</strong> model above. Store the results in an object named <strong>ridge.cv</strong>.</p>
<p>Then use the <code>cbind()</code> funtion to display the <code>ridge.cv$lambda</code> and <code>ridge.cv$cvm</code> results together. Label the two columns “Lambda” and “10FCV” respectively</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>) <span class="co"># assign set seed</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ridge.cv <span class="ot">&lt;-</span> glmnet<span class="sc">::</span><span class="fu">cv.glmnet</span>(x, y, <span class="at">alpha =</span> <span class="dv">0</span>) <span class="co"># apply cross validation</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">Lambda =</span> ridge.cv<span class="sc">$</span>lambda, <span class="st">`</span><span class="at">10FCV</span><span class="st">`</span> <span class="ot">=</span> ridge.cv<span class="sc">$</span>cvm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Lambda    10FCV
  [1,] 3275262.2859 14991855
  [2,] 2984297.0115 14957827
  [3,] 2719180.2900 14948481
  [4,] 2477615.8074 14943973
  [5,] 2257511.2477 14939030
  [6,] 2056960.1704 14933609
  [7,] 1874225.4981 14927666
  [8,] 1707724.4704 14921150
  [9,] 1556014.9352 14914007
 [10,] 1417782.8569 14906178
 [11,] 1291830.9354 14897597
 [12,] 1177068.2356 14888195
 [13,] 1072500.7377 14877892
 [14,]  977222.7281 14866606
 [15,]  890408.9542 14854245
 [16,]  811307.4768 14840708
 [17,]  739233.1566 14825887
 [18,]  673561.7204 14809664
 [19,]  613724.3536 14791910
 [20,]  559202.7735 14772488
 [21,]  509524.7403 14751246
 [22,]  464259.9667 14728021
 [23,]  423016.3908 14702638
 [24,]  385436.7805 14674907
 [25,]  351195.6393 14644623
 [26,]  319996.3866 14611567
 [27,]  291568.7896 14575503
 [28,]  265666.6219 14536180
 [29,]  242065.5314 14493328
 [30,]  220561.0968 14446661
 [31,]  200967.0568 14395876
 [32,]  183113.6974 14340652
 [33,]  166846.3812 14280650
 [34,]  152024.2085 14215516
 [35,]  138518.7968 14144879
 [36,]  126213.1687 14068356
 [37,]  115000.7387 13985549
 [38,]  104784.3900 13896053
 [39,]   95475.6336 13799454
 [40,]   86993.8414 13695336
 [41,]   79265.5483 13583284
 [42,]   72223.8155 13462890
 [43,]   65807.6508 13333757
 [44,]   59961.4804 13195509
 [45,]   54634.6678 13047796
 [46,]   49781.0745 12890304
 [47,]   45358.6610 12722761
 [48,]   41329.1226 12544952
 [49,]   37657.5573 12356725
 [50,]   34312.1637 12158001
 [51,]   31263.9656 11948789
 [52,]   28486.5611 11729192
 [53,]   25955.8935 11499412
 [54,]   23650.0435 11259773
 [55,]   21549.0388 11010716
 [56,]   19634.6816 10752805
 [57,]   17890.3906 10486735
 [58,]   16301.0576 10213329
 [59,]   14852.9165  9933534
 [60,]   13533.4244  9648416
 [61,]   12331.1523  9359147
 [62,]   11235.6867  9066994
 [63,]   10237.5392  8773300
 [64,]    9328.0645  8479461
 [65,]    8499.3849  8186904
 [66,]    7744.3230  7897061
 [67,]    7056.3387  7611344
 [68,]    6429.4730  7331115
 [69,]    5858.2963  7057664
 [70,]    5337.8614  6792184
 [71,]    4863.6605  6535755
 [72,]    4431.5863  6289323
 [73,]    4037.8964  6053693
 [74,]    3679.1808  5829537
 [75,]    3352.3326  5617359
 [76,]    3054.5206  5417433
 [77,]    2783.1654  5229999
 [78,]    2535.9166  5055114
 [79,]    2310.6328  4892707
 [80,]    2105.3625  4742589
 [81,]    1918.3279  4604470
 [82,]    1747.9090  4477968
 [83,]    1592.6296  4362626
 [84,]    1451.1447  4257926
 [85,]    1322.2290  4163304
 [86,]    1204.7659  4078160
 [87,]    1097.7378  4001870
 [88,]    1000.2178  3933801
 [89,]     911.3612  3873318
 [90,]     830.3984  3819793
 [91,]     756.6281  3772613
 [92,]     689.4113  3731186
 [93,]     628.1659  3694949
 [94,]     572.3614  3663368
 [95,]     521.5144  3635952
 [96,]     475.1845  3612215
 [97,]     432.9704  3591744
 [98,]     394.5065  3574132
 [99,]     359.4596  3559042
[100,]     327.5262  3545828</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ridge.cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW3_O-Malley_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>4.4 It should be obvious from the output above that the best lambda will be quite small. Let’s find it. Find the <strong>best lambda</strong> and store it in an object named <strong>ridge.bestlam</strong>. Then find the minimum cross-validation MSE with <code>min(ridge.cv$cvm)</code> and store the results in an object named <strong>min.mse</strong>. Display the resulting two values together using the <code>cbind()</code> function, with proper labels</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>ridge.bestlam <span class="ot">&lt;-</span> ridge.cv<span class="sc">$</span>lambda[<span class="fu">which.min</span>(ridge.cv<span class="sc">$</span>cvm)] <span class="co"># find best lambda</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>min.mse <span class="ot">&lt;-</span> <span class="fu">min</span>(ridge.cv<span class="sc">$</span>cvm) <span class="co"># find minimum mse</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="st">`</span><span class="at">Best Lambda</span><span class="st">`</span> <span class="ot">=</span> ridge.bestlam, <span class="st">`</span><span class="at">Minimum MSE</span><span class="st">`</span> <span class="ot">=</span> min.mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Best Lambda Minimum MSE
[1,]    327.5262     3545828</code></pre>
</div>
</div>
<p>4.5 Now, extract the <strong>coefficients</strong> for the Ridge regression with the best lambda you just found above and name the coefficient vector <strong>ridge.coef</strong>. You can use the <code>predict()</code> or <code>coef()</code> functions with <code>s=bestlam</code> for this purpose. Then extract the <strong>OLS</strong> coefficients using <code>s=0</code> and name this vector <strong>ols.coef</strong>. List the two sets of coefficients side by side using the <code>cbind()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>ridge.coef <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">coef</span>(ridge.cv, <span class="at">s =</span> ridge.bestlam) <span class="co"># extract coefficients for best lambda</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>ols.coef <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">coef</span>(ridge.cv, <span class="at">s =</span> <span class="dv">0</span>) <span class="co"># extract ols coefficients</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="st">`</span><span class="at">Ridge Coefficients</span><span class="st">`</span> <span class="ot">=</span> ridge.coef, <span class="st">`</span><span class="at">OLS Coefficients</span><span class="st">`</span> <span class="ot">=</span> ols.coef)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>9 x 2 sparse Matrix of class "dgCMatrix"
                        s1             s1
(Intercept) -3955.50061103 -3955.50061103
Enroll          3.09324335     3.09324335
Top10perc      18.12887428    18.12887428
Outstate       -0.03810031    -0.03810031
Room.Board      0.38848585     0.38848585
PhD             3.59405610     3.59405610
S.F.Ratio      53.94981532    53.94981532
Expend          0.08996626     0.08996626
Grad.Rate      13.12904964    13.12904964</code></pre>
</div>
</div>
<p>4.6 Is there much difference between the Ridge and OLS regression coefficients? Why do you think that is?</p>
<section id="analysis-5" class="level4">
<h4 class="anchored" data-anchor-id="analysis-5">Analysis</h4>
<p>There is no difference between the Ridge and OLS regression coefficients. This is because we have already removed the variables that are highly correlated to reduce multicollinearity.</p>
<p>4.7 Which of the two models would you chose and why?</p>
</section>
<section id="analysis-6" class="level4">
<h4 class="anchored" data-anchor-id="analysis-6">Analysis</h4>
<p>I would choose the OLS model because it is simpler and easier to interpret. We have adequately addressed multicollinearity, so the added complexity of the ridge regression does not make sense in this case.</p>
<p>4.8 Using the Ridge model with the best lambda, interpret the coefficient for the predictor <strong>PhD</strong>. To answer this, review the documentation for the <strong>College</strong> data set and articulate your interpretation correctly.</p>
</section>
<section id="analysis-7" class="level4">
<h4 class="anchored" data-anchor-id="analysis-7">Analysis</h4>
<p>For every 1% increase of the number of college professors with a PhD there is an 3.5 unit increase in the number of applications received.</p>
<p>4.9 <strong>LASSO</strong> Illustration (only, not required)</p>
<p>This is not required for this homework, but you should try this on your own. Try the model above with LASSO instead of Ridge simply by copying and pasting all the commands above and changing <strong>alpha</strong> from 0 to 1. You may want to name your objects differently.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO Example done for you</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># I'm not repeating some of the lines above because LASSO is using the same libraries and model matrices</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Just change alpha from 0 to 1</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>lasso.mod <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x, y, <span class="at">alpha=</span><span class="dv">1</span>) </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross-validation</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>lasso.cv<span class="ot">=</span><span class="fu">cv.glmnet</span>(x,y,<span class="at">alpha=</span><span class="dv">1</span>) </span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso.cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW3_O-Malley_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Best Lambda</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lasso.bestlam <span class="ot">&lt;-</span> lasso.cv<span class="sc">$</span>lambda.min </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>min.mse<span class="ot">=</span><span class="fu">min</span>(lasso.cv<span class="sc">$</span>cvm)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="st">"Best LASSO Lambda"</span><span class="ot">=</span>lasso.bestlam, <span class="st">"Best LASSO MSE"</span><span class="ot">=</span>min.mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Best LASSO Lambda Best LASSO MSE
[1,]          6.429473        3485673</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO yields a smaller MSE=3.4M compared to Ridge's MSE=3.6M. LASSO is slightly better in this case.</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>lasso.coef <span class="ot">&lt;-</span> <span class="fu">coef</span>(lasso.mod, <span class="at">s=</span>lasso.bestlam)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternatively, predict(lasso.mod, type="coefficients", s=bestlam)</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Listing Ridge, LASSO and OLS coefficients together</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(ridge.coef, lasso.coef, ols.coef)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>9 x 3 sparse Matrix of class "dgCMatrix"
                        s1             s1             s1
(Intercept) -3955.50061103 -3859.57704167 -3955.50061103
Enroll          3.09324335     3.41358000     3.09324335
Top10perc      18.12887428    15.52752372    18.12887428
Outstate       -0.03810031    -0.02819657    -0.03810031
Room.Board      0.38848585     0.42387306     0.38848585
PhD             3.59405610    -2.99282571     3.59405610
S.F.Ratio      53.94981532    43.59455293    53.94981532
Expend          0.08996626     0.09267400     0.08996626
Grad.Rate      13.12904964    14.14731860    13.12904964</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comment FYI: the relative importance of the coefficients are similar among all three models, Ridge, LASSO and OLS, mainly because there was little shrinkage. Notice that different coefficients have shrunk at different rates. Also, note that due to the complex math involved in minimizing the SSE plus penalties, some coefficients may grow a bit before they shrink. The final size of the coefficients is less important because Ridge and LASSO yield “biased” coefficients, so you must interpret these with caution. The best lambda only ensures that predictions have the lowest MSE, so that the predictive accuracy of the model improves. The coefficients should only provide a general direction of results, but again, don’t bet on them because they are biased (sometimes they even change signs).</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="pts.-pcr-and-pls" class="level2">
<h2 class="anchored" data-anchor-id="pts.-pcr-and-pls">5. (20 pts.) PCR and PLS</h2>
<p>5.1 First, read the <strong>PizzaCal.csv</strong> file. After reading the file, open and inspect it to be sure that you read it correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>pizza <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"/Users/coniecakes/Library/CloudStorage/OneDrive-Personal/001. Documents - Main/023. Programming Tools/R Studio/PredictiveAnalytics/Homework/data/PizzaCal.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">row.names=</span><span class="dv">1</span>, <span class="at">sep=</span><span class="st">","</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Note on row.names=1 - the first column has pizza ID's, which are not really data to analyze, just row labels. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This file contains nutrition data on a sample of 300 slices of frozen pizza (100 grams each):</p>
<ul>
<li><strong>brand</strong>: categorical variable with brand labels</li>
<li><strong>import</strong>: binary variable, 0 if domestic, 1 if imported</li>
<li><strong>cal</strong>: number of caloerries in the slice</li>
</ul>
<p>All remaining measures are in grams, per slice:</p>
<ul>
<li><strong>mois</strong>: moisture content</li>
<li><strong>prot</strong>: amount of protein</li>
<li><strong>fat</strong>: fat content</li>
<li><strong>ash</strong>: ash content</li>
<li><strong>sodium</strong>: amount of sodium</li>
<li><strong>carb</strong>: amount of carbohydrates</li>
</ul>
<p>You can explore the correlation matrix of this data set on your own (NOT in this script). and you will find that the variables are highly correlated. So, PCR or PLS would be good methods to use.</p>
<p>5.2 Principal Components Regression (PCR)</p>
<p>Load the <strong>{pls}</strong> library and fit a <strong>PCR</strong> model using the <code>pcr()</code> function to predict calories <strong>cal</strong> using all the remaining variables as predictors and the full data set. Use the <strong>LOOCV</strong> validation this time <code>scale=T, validation="LOO"</code>. Store the results in an object named <strong>pcr.fit</strong>. Then inspect the results with a <code>validationplot()</code> and displaying its <code>summary()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pls)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>pcr.fit <span class="ot">&lt;-</span> pls<span class="sc">::</span><span class="fu">pcr</span>(cal <span class="sc">~</span> . , <span class="at">data =</span> pizza, <span class="at">scale=</span>T, <span class="at">validation=</span><span class="st">"LOO"</span>) <span class="co"># fit pcr model</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>pls<span class="sc">::</span><span class="fu">validationplot</span>(pcr.fit) <span class="co"># view validation plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW3_O-Malley_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pcr.fit) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 300 16 
    Y dimension: 300 1
Fit method: svdpc
Number of components considered: 16

VALIDATION: RMSEP
Cross-validated using 300 leave-one-out segments.
       (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
CV           62.11    61.96    22.52    21.77    16.53    15.83    15.84
adjCV        62.11    61.96    22.52    21.77    16.52    15.83    15.84
       7 comps  8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
CV       15.89    15.84     10.7     2.916     2.908     1.648     1.613
adjCV    15.89    15.84     10.7     2.916     2.907     1.648     1.613
       14 comps  15 comps  16 comps
CV         1.61     1.635     1.634
adjCV      1.61     1.634     1.633

TRAINING: % variance explained
     1 comps  2 comps  3 comps  4 comps  5 comps  6 comps  7 comps  8 comps
X     29.970    48.10    57.71    65.69    72.84    79.83    86.78    93.71
cal    1.878    87.09    88.00    93.20    93.84    93.84    93.85    93.85
     9 comps  10 comps  11 comps  12 comps  13 comps  14 comps  15 comps
X      99.35     99.75     99.87     99.93     99.99    100.00    100.00
cal    97.21     99.79     99.80     99.93     99.94     99.94     99.94
     16 comps
X      100.00
cal     99.94</code></pre>
</div>
</div>
<p>5.3 Choose 3 to 5 candidate models with different number of components, based on the scree plot and the summary output above. Provide a brief rationale for you selection of candidate models. In your answer, please refer to the “elbows” in the scree plot, the cross-validation (CV values of the RMSEP), and the % explained variance of the various components.</p>
<section id="analysis-8" class="level4">
<h4 class="anchored" data-anchor-id="analysis-8">Analysis</h4>
<p>There appear to be elbows at 2, 4, 5, 10, and 12 components. The 12 component has the lowest CV value, but does not provide a significant enough increase in % variance explained in X or the response variable <code>cal</code>. In an effort to balance simplicity with predictive power, we should choose the 10 component model. The 2 and 4 component models have much higher RMSE values and lower explanatory power compared to the 10 component model. However, the high explanatory values could be indicative of overfitting.</p>
<p>5.4 Coefficients</p>
<p>Regardless of your answer above, let’s explore a few models at each of the elbows, with 2, 4 and 10 components, and also for 5 components. Use the <code>pcr.fit$coefficients</code> attribute, but use <code>[,,c(2,4,5,10)]</code> as the index.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>pcr.fit<span class="sc">$</span>coefficients[,,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">10</span>)] <span class="co"># review coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           2 comps      4 comps     5 comps    10 comps
brandB  -0.3785743   0.77780540   2.4712379  -5.8356727
brandC  -4.7900960  -7.41263348  -4.9424732  -2.7566859
brandD  -1.7397922  -0.58938831  -3.5713006  -1.9249543
brandE  -3.0340624   2.39375786   2.6916871   2.6425361
brandF   6.7072207   2.88741929   2.9757668   0.4951699
brandG   6.6170059   3.44215201   3.2781923   0.9803379
brandH  -3.7505411   2.72729146   3.3191092   3.0313570
brandI  -8.7327146 -15.41874132 -15.8352175  -6.7959737
brandJ  -4.6193218  -4.27143837  -5.7099818  -2.3600348
import  17.7594983  14.03872855  14.0242103   9.1788238
mois   -15.1395782 -17.74148471 -17.7480890 -24.4265638
prot     1.1313916   0.02268209   0.2152082  -4.7858508
fat     13.2293389  15.08282179  15.4779708  45.7709229
ash      6.0613614   6.48278909   5.8815908  -7.4450275
sodium  12.2702088  13.96995718  13.8973738  -1.4912227
carb     0.6065962   1.42992934   1.2098732  -7.5945828</code></pre>
</div>
</div>
<p>5.5 Which of these models would you select? Provide a concise but clear rationale for your selection. Refer to the bias vs.&nbsp;variance tradeoff and also to the cross-validation RMSE in your answer.</p>
</section>
<section id="analysis-9" class="level4">
<h4 class="anchored" data-anchor-id="analysis-9">Analysis</h4>
<p>I would chose the 5 component model because it best balances simplicity with explanatory power. There is great explanatory power with a small RMSE (93.84% and 15.83, respectively). This high explanatory power may be because the model is overfit and there will be higher variance when new data is introduced to the model.</p>
<p>5.6 Regardless of your answer above, to illustrate a simpler example, let’s fit a model with <strong>5 components</strong> only, using the <code>ncomp=5</code> attribute in the <code>pcr()</code> function. Name this model <strong>pcr.fit.5</strong>. Then display its <code>summary()</code>, the component <code>$loadings</code> and the resulting coefficients for 5 components, using the <code>coef()</code> function with the <code>ncomp=5</code> attribute.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>pcr.fit<span class="fl">.5</span> <span class="ot">&lt;-</span> pls<span class="sc">::</span><span class="fu">pcr</span>(cal <span class="sc">~</span> ., <span class="at">data =</span> pizza, <span class="at">scale=</span>T, <span class="at">validation=</span><span class="st">"LOO"</span>, <span class="at">ncomp=</span><span class="dv">5</span>) <span class="co"># fit 5 coefficient model</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pcr.fit<span class="fl">.5</span>) <span class="co"># view summary statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 300 16 
    Y dimension: 300 1
Fit method: svdpc
Number of components considered: 5

VALIDATION: RMSEP
Cross-validated using 300 leave-one-out segments.
       (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps
CV           62.11    61.96    22.52    21.77    16.53    15.83
adjCV        62.11    61.96    22.52    21.77    16.52    15.83

TRAINING: % variance explained
     1 comps  2 comps  3 comps  4 comps  5 comps
X     29.970    48.10    57.71    65.69    72.84
cal    1.878    87.09    88.00    93.20    93.84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>pcr.fit<span class="fl">.5</span><span class="sc">$</span>loadings <span class="co"># view loading components</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
       Comp 1 Comp 2 Comp 3 Comp 4 Comp 5
brandB  0.156        -0.478         0.368
brandC  0.139  0.159  0.542         0.537
brandD  0.185         0.252  0.188 -0.648
brandE -0.132        -0.113  0.391       
brandF -0.176 -0.220  0.138 -0.252       
brandG -0.182 -0.218  0.181 -0.185       
brandH -0.155                0.486  0.129
brandI         0.257 -0.112 -0.577       
brandJ         0.135 -0.182        -0.313
import        -0.539  0.133 -0.246       
mois    0.221  0.476        -0.242       
prot    0.395         0.390              
fat     0.325 -0.356 -0.183              
ash     0.436 -0.130               -0.131
sodium  0.321 -0.328 -0.291              
carb   -0.450                            

               Comp 1 Comp 2 Comp 3 Comp 4 Comp 5
SS loadings     1.000  1.000  1.000  1.000  1.000
Proportion Var  0.062  0.062  0.062  0.062  0.062
Cumulative Var  0.062  0.125  0.187  0.250  0.312</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">coef</span>(pcr.fit<span class="fl">.5</span>, <span class="at">ncomp=</span><span class="dv">5</span>) <span class="co"># view coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , 5 comps

               cal
brandB   2.4712379
brandC  -4.9424732
brandD  -3.5713006
brandE   2.6916871
brandF   2.9757668
brandG   3.2781923
brandH   3.3191092
brandI -15.8352175
brandJ  -5.7099818
import  14.0242103
mois   -17.7480890
prot     0.2152082
fat     15.4779708
ash      5.8815908
sodium  13.8973738
carb     1.2098732</code></pre>
</div>
</div>
<p>5.7 <strong>PLS</strong> Illustration (only, not required)</p>
<p>This is not required for this homework, but you should try this on your own. Try the model above with LASSO instead of Ridge simply by copying and pasting all the commands above, but using the <code>plsr()</code> function rather than the <code>pcr()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Done for you</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>pls.fit <span class="ot">&lt;-</span> <span class="fu">plsr</span>(cal<span class="sc">~</span>., <span class="at">data=</span>pizza, <span class="at">scale=</span><span class="cn">TRUE</span>, <span class="at">validation=</span><span class="st">"LOO"</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">validationplot</span>(pls.fit, <span class="at">val.type=</span><span class="st">"RMSEP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW3_O-Malley_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pls.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 300 16 
    Y dimension: 300 1
Fit method: kernelpls
Number of components considered: 16

VALIDATION: RMSEP
Cross-validated using 300 leave-one-out segments.
       (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
CV           62.11    16.82    13.04    9.944    8.835    4.805    2.546
adjCV        62.11    16.82    13.04    9.944    8.835    4.804    2.546
       7 comps  8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
CV       2.515    1.636    1.622     1.611     1.611     1.611     1.611
adjCV    2.515    1.636    1.622     1.611     1.611     1.611     1.611
       14 comps  15 comps  16 comps
CV         1.61     1.635     3.169
adjCV      1.61     1.634     2.401

TRAINING: % variance explained
     1 comps  2 comps  3 comps  4 comps  5 comps  6 comps  7 comps  8 comps
X      18.60    43.16    55.36    61.85    65.24    71.66    78.84    78.99
cal    92.86    95.79    97.60    98.12    99.44    99.84    99.85    99.94
     9 comps  10 comps  11 comps  12 comps  13 comps  14 comps  15 comps
X      85.90     86.11     92.99     93.30     99.97    100.00    100.00
cal    99.94     99.94     99.94     99.94     99.94     99.94     99.94
     16 comps
X      100.00
cal     99.94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(pls.fit, <span class="at">ncomp=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , 8 comps

                cal
brandB  -0.05993157
brandC   0.31246842
brandD   0.05053764
brandE   0.22782099
brandF   0.76979764
brandG   0.38511258
brandH   0.05165808
brandI   0.12486055
brandJ   0.04208060
import  -0.48123863
mois   -38.85688734
prot    -0.90235720
fat     44.55830540
ash     -4.39025658
sodium  -0.05192838
carb    -0.97682444</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># It looks like the 8 component model is optimal, with a CV RMSE of 1.636 and 78.99% of the variance explained. Which model would you choose, PCR with 10 components or PLS with 8 components? Why?</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The PCR model with 10 components has a CV RMSE of 2.016 and 99.75 of explained variance. The PLS model with 8 components has a CV RMSE of 1.636, but it only explains 78.99% of the variance. This is to be expected, because PLS aligns better with the response variable, but the components are not exactly principal components. I would select the PLS model because it has a lower CV RMSE. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>